// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"red-feed/interactive/events"
	"red-feed/interactive/grpc"
	"red-feed/interactive/ioc"
	"red-feed/interactive/repository"
	"red-feed/interactive/repository/cache"
	"red-feed/interactive/repository/dao"
	"red-feed/interactive/service"
)

// Injectors from wire.go:

func InitAPP() *App {
	db := ioc.InitDB()
	interactiveDAO := dao.NewInteractiveDAO(db)
	cmdable := ioc.InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	logger := ioc.InitLogger()
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service.NewInteractiveService(interactiveRepository, logger)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	server := ioc.InitGRPCXServer(interactiveServiceServer)
	client := ioc.InitKafka()
	consumer := events.NewInteractiveReadEventConsumer(client, logger, interactiveRepository)
	v := ioc.NewConsumers(consumer)
	app := &App{
		server:    server,
		consumers: v,
	}
	return app
}

// wire.go:

var thirdPartySet = wire.NewSet(ioc.InitDB, ioc.InitLogger, ioc.InitKafka, ioc.InitRedis)

var interactiveSvcProvider = wire.NewSet(service.NewInteractiveService, repository.NewInteractiveRepository, dao.NewInteractiveDAO, cache.NewRedisInteractiveCache)
