// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"red-feed/internal/repository"
	"red-feed/internal/repository/cache"
	"red-feed/internal/repository/dao"
	"red-feed/internal/service"
	"red-feed/internal/web"
	"red-feed/internal/web/jwt"
	"red-feed/ioc"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	handler := ijwt.NewRedisJWTHandler(cmdable)
	logger := ioc.InitLogger()
	v := ioc.InitMiddlewares(cmdable, handler, logger)
	db := ioc.InitDB()
	gormUserDAO := dao.NewUserDAO(db)
	redisUserCache := cache.NewUserCache(cmdable)
	cachedUserRepository := repository.NewUserRepository(gormUserDAO, redisUserCache)
	userService := service.NewUserService(cachedUserRepository)
	smsService := ioc.InitSMSService()
	redisCodeCache := cache.NewCodeCache(cmdable)
	cachedCodeRepository := repository.NewCodeRepository(redisCodeCache)
	codeService := service.NewCodeService(smsService, cachedCodeRepository)
	userHandler := web.NewUserHandler(userService, codeService, handler)
	wechatService := ioc.InitWechatService(logger)
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userService)
	engine := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler)
	return engine
}
