// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"red-feed/internal/repository"
	"red-feed/internal/repository/dao"
	"red-feed/internal/service"
	"red-feed/internal/web"
)

// Injectors from wire.go:

func InitArticleHandler() *web.ArticleHandler {
	db := InitTestDB()
	articleDao := dao.NewGORMArticleDao(db)
	articleRepository := repository.NewArticleRepository(articleDao)
	articleService := service.NewArticleService(articleRepository)
	logger := InitTestLogger()
	articleHandler := web.NewArticleHandler(articleService, logger)
	return articleHandler
}

// wire.go:

var thirdProvider = wire.NewSet(InitRedis, InitTestDB, InitTestLogger)
